// Famous personalities born in or strongly associated with Hyderabad
// Public domain biographical facts

export interface FamousPersonality {
  id: string;
  name: string;
  category: 'sports' | 'cinema' | 'politics' | 'science' | 'business' | 'literature' | 'music' | 'other';
  bornYear: number | null;
  area: string | null;
  notable: string;
  bio: string;
}

export const PERSONALITIES: FamousPersonality[] = [
  {
    id: 'sania-mirza',
    name: 'Sania Mirza',
    category: 'sports',
    bornYear: 1986,
    area: 'Hyderabad',
    notable: '6-time Grand Slam doubles champion, Padma Bhushan recipient',
    bio: 'Former world No. 1 doubles tennis player and one of India\'s most celebrated sportspersons. Grew up and trained in Hyderabad.',
  },
  {
    id: 'pv-sindhu',
    name: 'P. V. Sindhu',
    category: 'sports',
    bornYear: 1995,
    area: 'Secunderabad',
    notable: '2020 Olympic bronze, 2016 Olympic silver, BWF World Champion',
    bio: 'Two-time Olympic medallist in badminton, trained at the Pullela Gopichand Academy in Hyderabad.',
  },
  {
    id: 'saina',
    name: 'Saina Nehwal',
    category: 'sports',
    bornYear: 1990,
    area: 'Hyderabad',
    notable: '2012 Olympic bronze, former world No. 1',
    bio: 'First Indian badminton player to win an Olympic medal. Longtime Hyderabad resident and Gopichand Academy trainee.',
  },
  {
    id: 'vvs-laxman',
    name: 'V. V. S. Laxman',
    category: 'sports',
    bornYear: 1974,
    area: 'Hyderabad',
    notable: 'India Test cricketer, famous 281 vs Australia',
    bio: 'Elegant middle-order batsman known for his match-winning performances in Test cricket. Born and raised in Hyderabad.',
  },
  {
    id: 'azhar',
    name: 'Mohammad Azharuddin',
    category: 'sports',
    bornYear: 1963,
    area: 'Hyderabad',
    notable: 'Former Indian cricket team captain',
    bio: 'Stylish middle-order batsman and captain of the Indian cricket team in the 1990s.',
  },
  {
    id: 'cvr',
    name: 'C. V. Raman',
    category: 'science',
    bornYear: 1888,
    area: 'Associated',
    notable: 'Nobel Prize in Physics (1930)',
    bio: 'Indian physicist who won the Nobel Prize for his work on light scattering (Raman Effect).',
  },
  {
    id: 'prasad',
    name: 'L. V. Prasad',
    category: 'cinema',
    bornYear: 1908,
    area: 'Hyderabad',
    notable: 'Founder of L. V. Prasad Eye Institute',
    bio: 'Legendary filmmaker and founder of Prasad Studios; lent his name to one of the world\'s most respected eye hospitals in Hyderabad.',
  },
  {
    id: 'snr',
    name: 'Akkineni Nageswara Rao',
    category: 'cinema',
    bornYear: 1923,
    area: 'Hyderabad',
    notable: 'Dadasaheb Phalke awardee, Telugu cinema legend',
    bio: 'Iconic Telugu film actor and founder of Annapurna Studios in Hyderabad. Father of actor Nagarjuna.',
  },
  {
    id: 'ntr',
    name: 'N. T. Rama Rao',
    category: 'cinema',
    bornYear: 1923,
    area: 'Associated',
    notable: 'Former Chief Minister of Andhra Pradesh',
    bio: 'Telugu film icon and founder of TDP. Served three terms as Chief Minister of undivided Andhra Pradesh from Hyderabad.',
  },
  {
    id: 'allu-arjun',
    name: 'Allu Arjun',
    category: 'cinema',
    bornYear: 1982,
    area: 'Hyderabad',
    notable: 'National Film Award for Best Actor',
    bio: 'Telugu film actor, winner of the National Film Award for Best Actor for "Pushpa: The Rise".',
  },
  {
    id: 'chiru',
    name: 'Chiranjeevi',
    category: 'cinema',
    bornYear: 1955,
    area: 'Hyderabad',
    notable: 'Padma Vibhushan, Telugu cinema superstar',
    bio: '"Megastar" of Telugu cinema with over 150 films. Received the Padma Vibhushan in 2024.',
  },
  {
    id: 'nagarjuna',
    name: 'Akkineni Nagarjuna',
    category: 'cinema',
    bornYear: 1959,
    area: 'Hyderabad',
    notable: 'Telugu film actor and producer',
    bio: 'Leading actor in Telugu and Hindi cinema, runs Annapurna Studios in Hyderabad.',
  },
  {
    id: 'satya',
    name: 'Satya Nadella',
    category: 'business',
    bornYear: 1967,
    area: 'Hyderabad',
    notable: 'Chairman & CEO, Microsoft',
    bio: 'Born and educated in Hyderabad (HPS Begumpet, Manipal Institute of Technology). Became Microsoft CEO in 2014.',
  },
  {
    id: 'shantanu',
    name: 'Shantanu Narayen',
    category: 'business',
    bornYear: 1963,
    area: 'Hyderabad',
    notable: 'Chairman & CEO, Adobe Inc.',
    bio: 'Born and raised in Hyderabad. CEO of Adobe since 2007, on the board of Pfizer.',
  },
  {
    id: 'prannoy',
    name: 'Prannoy Roy',
    category: 'other',
    bornYear: 1949,
    area: 'Associated',
    notable: 'Co-founder of NDTV',
    bio: 'Indian journalist, psephologist and co-founder of NDTV.',
  },
  {
    id: 'raghunath',
    name: 'Mekala Jaya Raghunath',
    category: 'literature',
    bornYear: 1940,
    area: 'Hyderabad',
    notable: 'Telugu poet and literary critic',
    bio: 'Respected Telugu literary figure whose work reflects Telangana culture and social movements.',
  },
  {
    id: 'tabu',
    name: 'Tabu',
    category: 'cinema',
    bornYear: 1971,
    area: 'Hyderabad',
    notable: 'Padma Shri, National Film Award winner',
    bio: 'Hindi and Telugu film actor born in Hyderabad. Awarded Padma Shri and two National Film Awards.',
  },
  {
    id: 'samantha',
    name: 'Samantha Ruth Prabhu',
    category: 'cinema',
    bornYear: 1987,
    area: 'Hyderabad',
    notable: 'Telugu and Tamil film actor',
    bio: 'Leading South Indian cinema actor based in Hyderabad, also known for her OTT work.',
  },
];
