// Government schemes available to Hyderabad residents
// Mix of Central Government, Telangana State, and GHMC schemes

export interface Scheme {
  id: string;
  name: string;
  nameEn: string;
  category: 'welfare' | 'housing' | 'health' | 'education' | 'agriculture' | 'employment' | 'women' | 'senior' | 'energy';
  level: 'central' | 'state' | 'city';
  department: string;
  description: string;
  benefit: string;
  eligibility: string;
  applyUrl: string;
  helpline: string | null;
  active: boolean;
  beneficiariesLakh: number | null;
}

export const SCHEMES: Scheme[] = [
  // === TELANGANA STATE SCHEMES (Congress government "Six Guarantees") ===
  {
    id: 'mahalakshmi',
    name: 'Mahalakshmi Scheme',
    nameEn: 'Mahalakshmi (Six Guarantees)',
    category: 'women',
    level: 'state',
    department: 'Women Development & Child Welfare, Telangana',
    description: 'Monthly financial support to women, free bus travel in TGSRTC buses, and subsidised LPG cylinders.',
    benefit: '₹2,500/month per woman + free bus travel + ₹500 LPG cylinder',
    eligibility: 'Women residents of Telangana',
    applyUrl: 'https://telangana.gov.in',
    helpline: '1800-425-0033',
    active: true,
    beneficiariesLakh: 175,
  },
  {
    id: 'rythu-bharosa',
    name: 'Rythu Bharosa',
    nameEn: 'Rythu Bharosa (Farmer Support)',
    category: 'agriculture',
    level: 'state',
    department: 'Agriculture Department, Telangana',
    description: 'Investment support for farmers per acre of land owned.',
    benefit: '₹12,000 per acre per year (₹6,000 per season)',
    eligibility: 'Farmers with land records in Telangana',
    applyUrl: 'https://rythubandhu.telangana.gov.in',
    helpline: '1800-425-1110',
    active: true,
    beneficiariesLakh: 70,
  },
  {
    id: 'arogyasri',
    name: 'Rajiv Aarogyasri',
    nameEn: 'Rajiv Aarogyasri Health Scheme',
    category: 'health',
    level: 'state',
    department: 'Health & Family Welfare, Telangana',
    description: 'Cashless medical treatment up to ₹10 lakh at empaneled hospitals.',
    benefit: 'Cashless cover up to ₹10 lakh per family per year',
    eligibility: 'BPL and white ration card holders',
    applyUrl: 'https://www.aarogyasri.telangana.gov.in',
    helpline: '104',
    active: true,
    beneficiariesLakh: 90,
  },
  {
    id: 'cheyutha',
    name: 'Cheyutha Scheme',
    nameEn: 'Cheyutha (Senior Support)',
    category: 'senior',
    level: 'state',
    department: 'Women Development & Child Welfare, Telangana',
    description: 'Monthly pension for senior citizens, widows, disabled, and beedi workers.',
    benefit: '₹4,000/month pension',
    eligibility: 'Senior citizens (65+), widows, PwD',
    applyUrl: 'https://aasara.telangana.gov.in',
    helpline: '1800-425-0033',
    active: true,
    beneficiariesLakh: 44,
  },
  {
    id: 'gruha-jyothi',
    name: 'Gruha Jyothi',
    nameEn: 'Gruha Jyothi (Free Power)',
    category: 'energy',
    level: 'state',
    department: 'Energy Department, Telangana',
    description: 'Free household electricity up to 200 units per month.',
    benefit: 'Up to 200 units/month free electricity',
    eligibility: 'Telangana households with own meter',
    applyUrl: 'https://tgsouthernpower.org',
    helpline: '1912',
    active: true,
    beneficiariesLakh: 120,
  },
  {
    id: 'indiramma-housing',
    name: 'Indiramma Housing Scheme',
    nameEn: 'Indiramma Indlu Housing',
    category: 'housing',
    level: 'state',
    department: 'Housing Department, Telangana',
    description: 'Financial assistance for construction of a pucca house.',
    benefit: '₹5 lakh per house for construction',
    eligibility: 'BPL families without own pucca house',
    applyUrl: 'https://housing.telangana.gov.in',
    helpline: null,
    active: true,
    beneficiariesLakh: 4.5,
  },
  {
    id: 'kalyana-lakshmi',
    name: 'Kalyana Lakshmi',
    nameEn: 'Kalyana Lakshmi / Shaadi Mubarak',
    category: 'women',
    level: 'state',
    department: 'Minority Welfare / SC Welfare, Telangana',
    description: 'One-time financial assistance at the time of marriage of daughters.',
    benefit: '₹1,00,116 per bride',
    eligibility: 'SC/ST/BC/Minority families with income below threshold',
    applyUrl: 'https://klkmapps.telangana.gov.in',
    helpline: null,
    active: true,
    beneficiariesLakh: 12,
  },

  // === CENTRAL GOVERNMENT SCHEMES ===
  {
    id: 'pm-kisan',
    name: 'PM-KISAN',
    nameEn: 'Pradhan Mantri Kisan Samman Nidhi',
    category: 'agriculture',
    level: 'central',
    department: 'Ministry of Agriculture, GoI',
    description: 'Direct income support to small and marginal farmers.',
    benefit: '₹6,000/year in 3 installments',
    eligibility: 'Landholding farmer families',
    applyUrl: 'https://pmkisan.gov.in',
    helpline: '155261',
    active: true,
    beneficiariesLakh: 37,
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat',
    nameEn: 'PM Jan Arogya Yojana (Ayushman Bharat)',
    category: 'health',
    level: 'central',
    department: 'Ministry of Health & Family Welfare, GoI',
    description: 'Health cover for secondary and tertiary hospitalisation.',
    benefit: '₹5 lakh per family per year cashless cover',
    eligibility: 'Families in SECC 2011 deprivation criteria',
    applyUrl: 'https://pmjay.gov.in',
    helpline: '14555',
    active: true,
    beneficiariesLakh: 55,
  },
  {
    id: 'pmay-urban',
    name: 'PMAY (Urban)',
    nameEn: 'Pradhan Mantri Awas Yojana — Urban',
    category: 'housing',
    level: 'central',
    department: 'Ministry of Housing & Urban Affairs, GoI',
    description: 'Credit-linked subsidy and direct support for urban housing.',
    benefit: 'Interest subsidy up to ₹2.67 lakh / affordable housing',
    eligibility: 'EWS/LIG/MIG households',
    applyUrl: 'https://pmaymis.gov.in',
    helpline: '1800-11-3377',
    active: true,
    beneficiariesLakh: null,
  },
  {
    id: 'mgnrega',
    name: 'MGNREGA',
    nameEn: 'Mahatma Gandhi National Rural Employment Guarantee Act',
    category: 'employment',
    level: 'central',
    department: 'Ministry of Rural Development, GoI',
    description: 'Guarantees 100 days of wage employment per rural household.',
    benefit: '₹300/day (Telangana rate) × 100 days',
    eligibility: 'Rural households willing to do unskilled manual work',
    applyUrl: 'https://nrega.nic.in',
    helpline: '1800-345-22-44',
    active: true,
    beneficiariesLakh: 60,
  },
  {
    id: 'ujjwala',
    name: 'PM Ujjwala Yojana',
    nameEn: 'Pradhan Mantri Ujjwala Yojana',
    category: 'energy',
    level: 'central',
    department: 'Ministry of Petroleum & Natural Gas, GoI',
    description: 'Free LPG connection to women in BPL households.',
    benefit: 'Free LPG connection + subsidy on refills',
    eligibility: 'Women from BPL households',
    applyUrl: 'https://pmuy.gov.in',
    helpline: '1906',
    active: true,
    beneficiariesLakh: 15,
  },
  {
    id: 'sukanya',
    name: 'Sukanya Samriddhi Yojana',
    nameEn: 'Sukanya Samriddhi Yojana',
    category: 'women',
    level: 'central',
    department: 'Ministry of Finance, GoI',
    description: 'Small savings scheme for the girl child with tax benefits.',
    benefit: '8.2% interest p.a., tax-free on maturity',
    eligibility: 'Parents of a girl child below 10 years',
    applyUrl: 'https://www.indiapost.gov.in',
    helpline: '1924',
    active: true,
    beneficiariesLakh: null,
  },
];

export const SCHEME_CATEGORIES = [
  { id: 'welfare', label: 'Welfare', color: '#60A5FA' },
  { id: 'housing', label: 'Housing', color: '#F59E0B' },
  { id: 'health', label: 'Health', color: '#F87171' },
  { id: 'education', label: 'Education', color: '#A78BFA' },
  { id: 'agriculture', label: 'Agriculture', color: '#4ADE80' },
  { id: 'employment', label: 'Employment', color: '#34D399' },
  { id: 'women', label: 'Women', color: '#EC4899' },
  { id: 'senior', label: 'Senior Citizens', color: '#94A3B8' },
  { id: 'energy', label: 'Energy', color: '#FBBF24' },
] as const;
