// Citizen Services Guide — How to access government services in Hyderabad
// Sources: GHMC, Telangana e-Seva, MeeSeva, Public Services portals

export interface CitizenService {
  id: string;
  title: string;
  department: string;
  category: 'documents' | 'utilities' | 'civic' | 'property' | 'transport' | 'health' | 'business';
  description: string;
  steps: string[];
  documentsRequired: string[];
  feeInr: string;
  timelineDays: string;
  applyUrl: string;
  offlineLocation: string | null;
  helpline: string | null;
}

export const CITIZEN_SERVICES: CitizenService[] = [
  {
    id: 'aadhaar-update',
    title: 'Update Aadhaar Card',
    department: 'UIDAI',
    category: 'documents',
    description: 'Update name, address, mobile, date of birth or photo in Aadhaar.',
    steps: [
      'Visit nearest Aadhaar Seva Kendra or MeeSeva',
      'Fill Aadhaar update form with new details',
      'Provide supporting document proof',
      'Biometric verification',
      'Collect update receipt with URN',
      'Track status online using URN',
    ],
    documentsRequired: ['Existing Aadhaar', 'Proof of the detail being updated'],
    feeInr: '₹50 (biometric) / ₹25 (demographic)',
    timelineDays: '7-30 days',
    applyUrl: 'https://ssup.uidai.gov.in',
    offlineLocation: 'Aadhaar Seva Kendra, MeeSeva centres',
    helpline: '1947',
  },
  {
    id: 'birth-cert',
    title: 'Birth Certificate',
    department: 'GHMC',
    category: 'documents',
    description: 'Registration and download of birth certificate for births in GHMC limits.',
    steps: [
      'Register birth within 21 days at GHMC zonal office or hospital',
      'Submit parent details and hospital discharge summary',
      'Receive registration number',
      'Download certificate from GHMC portal after 7-10 days',
    ],
    documentsRequired: ['Discharge summary', 'Parent ID proof', 'Aadhaar'],
    feeInr: 'Free within 21 days; ₹100 thereafter',
    timelineDays: '7-10 days',
    applyUrl: 'https://www.ghmc.gov.in/BirthDeath/BirthCertificateSearch.aspx',
    offlineLocation: 'GHMC zonal offices',
    helpline: '040-21111111',
  },
  {
    id: 'death-cert',
    title: 'Death Certificate',
    department: 'GHMC',
    category: 'documents',
    description: 'Registration and certificate for deaths in GHMC limits.',
    steps: [
      'Register death within 21 days at the nearest GHMC office',
      'Submit medical certificate of cause of death',
      'Fill Form 2 (Death report)',
      'Download certificate from GHMC portal',
    ],
    documentsRequired: ['Medical certificate', 'ID proof of deceased and applicant'],
    feeInr: 'Free within 21 days; ₹100 thereafter',
    timelineDays: '7-10 days',
    applyUrl: 'https://www.ghmc.gov.in/BirthDeath/DeathCertificateSearch.aspx',
    offlineLocation: 'GHMC zonal offices',
    helpline: '040-21111111',
  },
  {
    id: 'property-tax',
    title: 'Pay Property Tax',
    department: 'GHMC',
    category: 'property',
    description: 'Pay annual property tax online for residential or commercial property.',
    steps: [
      'Visit GHMC online property tax portal',
      'Enter PTIN (Property Tax Identification Number)',
      'Verify owner and property details',
      'Pay via net banking / UPI / card',
      'Download receipt',
    ],
    documentsRequired: ['PTIN'],
    feeInr: 'As per property tax slab',
    timelineDays: 'Immediate',
    applyUrl: 'https://ptghmconlinepayment.cgg.gov.in',
    offlineLocation: 'GHMC mee-seva counters',
    helpline: '040-21111111',
  },
  {
    id: 'water-bill',
    title: 'Pay Water Bill',
    department: 'HMWSSB',
    category: 'utilities',
    description: 'Pay monthly water supply and sewerage bill for Hyderabad connections.',
    steps: [
      'Visit HMWSSB online portal',
      'Enter CAN (Customer Account Number)',
      'View bill and pay online',
      'Download receipt',
    ],
    documentsRequired: ['CAN'],
    feeInr: 'As per consumption slab',
    timelineDays: 'Immediate',
    applyUrl: 'https://onlinepayments.hyderabadwater.gov.in',
    offlineLocation: 'HMWSSB section offices',
    helpline: '155313',
  },
  {
    id: 'power-bill',
    title: 'Pay Electricity Bill',
    department: 'TGSPDCL',
    category: 'utilities',
    description: 'Pay monthly electricity bill for Hyderabad domestic/commercial connections.',
    steps: [
      'Visit TGSPDCL portal',
      'Enter unique service number',
      'Review bill',
      'Pay via UPI / net banking / card',
    ],
    documentsRequired: ['Service Number'],
    feeInr: 'As per consumption',
    timelineDays: 'Immediate',
    applyUrl: 'https://www.tgsouthernpower.org',
    offlineLocation: 'TGSPDCL section offices',
    helpline: '1912',
  },
  {
    id: 'trade-license',
    title: 'GHMC Trade Licence',
    department: 'GHMC',
    category: 'business',
    description: 'Obtain or renew trade licence for a business in GHMC limits.',
    steps: [
      'Visit GHMC trade licence portal',
      'Fill online application with business details',
      'Upload supporting documents',
      'Pay fee based on category and turnover',
      'Inspection and approval by GHMC',
      'Download licence certificate',
    ],
    documentsRequired: ['Rent/ownership proof', 'ID proof', 'NOC from owner', 'GST if applicable'],
    feeInr: 'Varies by category (₹500 - ₹25,000)',
    timelineDays: '15-30 days',
    applyUrl: 'https://www.ghmc.gov.in/tradelicence/login.aspx',
    offlineLocation: 'GHMC head office, zonal offices',
    helpline: '040-21111111',
  },
  {
    id: 'dl-rto',
    title: 'Driving Licence',
    department: 'Transport Dept, Telangana',
    category: 'transport',
    description: 'Apply for a new learner/permanent driving licence or renew existing.',
    steps: [
      'Apply online on Parivahan Sarathi portal',
      'Book RTO slot for learner test',
      'Pass learner test and get LL',
      'Practice for 30 days',
      'Book driving test slot',
      'Pass driving test to receive permanent licence',
    ],
    documentsRequired: ['Aadhaar', 'Age proof', 'Address proof', 'LL for permanent DL'],
    feeInr: '₹200 (LL) + ₹700 (DL)',
    timelineDays: '30-45 days',
    applyUrl: 'https://sarathi.parivahan.gov.in',
    offlineLocation: 'RTO offices (Khairatabad, Mehdipatnam, Malakpet, Uppal)',
    helpline: null,
  },
  {
    id: 'vehicle-reg',
    title: 'Vehicle Registration (TS Series)',
    department: 'Transport Dept, Telangana',
    category: 'transport',
    description: 'Register a new vehicle and get TS series number plate.',
    steps: [
      'Dealer initiates VAHAN application',
      'Pay road tax and registration fee',
      'Fitment of HSRP number plate',
      'Receive RC (Registration Certificate)',
    ],
    documentsRequired: ['Invoice', 'Insurance', 'Form 20', 'Address proof'],
    feeInr: 'Road tax % + ₹600 registration',
    timelineDays: '7-15 days',
    applyUrl: 'https://vahan.parivahan.gov.in',
    offlineLocation: 'RTO offices',
    helpline: null,
  },
  {
    id: 'ration-card',
    title: 'Ration Card (White/Pink)',
    department: 'Civil Supplies, Telangana',
    category: 'civic',
    description: 'Apply for new ration card or add/remove family members.',
    steps: [
      'Visit MeeSeva or epos.telangana.gov.in',
      'Fill application with Aadhaar-linked family details',
      'Submit supporting documents',
      'Field verification by MRO/tahsildar office',
      'Receive card after approval',
    ],
    documentsRequired: ['Aadhaar (all members)', 'Address proof', 'Income proof', 'Photograph'],
    feeInr: '₹25 at MeeSeva',
    timelineDays: '30-60 days',
    applyUrl: 'https://epos.telangana.gov.in',
    offlineLocation: 'MeeSeva centres, MRO offices',
    helpline: '1967',
  },
  {
    id: 'pension',
    title: 'Aasara Pension',
    department: 'Rural / Urban Development, Telangana',
    category: 'civic',
    description: 'Apply for old age, widow, disability, or beedi worker pension.',
    steps: [
      'Visit MeeSeva or Aasara portal',
      'Fill application form',
      'Provide Aadhaar, age/disability proof, bank details',
      'Field verification by MRO',
      'Monthly pension credited to linked bank account',
    ],
    documentsRequired: ['Aadhaar', 'Bank passbook', 'Age/disability certificate'],
    feeInr: 'Free',
    timelineDays: '30-90 days',
    applyUrl: 'https://aasara.telangana.gov.in',
    offlineLocation: 'MeeSeva centres',
    helpline: '1800-425-0033',
  },
  {
    id: 'basti-dawakhana',
    title: 'Visit Basti Dawakhana',
    department: 'Health & Family Welfare, Telangana',
    category: 'health',
    description: 'Access free primary healthcare and diagnostics at neighbourhood clinics.',
    steps: [
      'Walk into the nearest Basti Dawakhana',
      'Register at the counter with Aadhaar',
      'Consult the duty doctor',
      'Receive free medicines and basic diagnostics',
    ],
    documentsRequired: ['Aadhaar (preferred)'],
    feeInr: 'Free',
    timelineDays: 'Same day',
    applyUrl: 'https://health.telangana.gov.in',
    offlineLocation: '300+ Basti Dawakhanas across Hyderabad',
    helpline: '104',
  },
];
